[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:yaci-viewer]
command=node /app/cli.js --indexerBaseUrl http://localhost:3001/api/v1 --indexerWsUrl ws://localhost:3001/ws/liveblocks
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
